sudo: required #is required to use docker service in travis
language: java
jdk:
  - openjdk8
script:
  - gradle build
after_success:


notifications:
    email:
        recipients:
            - t8440304@gmail.com
        on_success: always
        on_failure: always