sudo: required #is required to use docker service in travis
language: java
jdk:
  - openjdk8
before_script:
  - export TRAVIS_AWS_ACCESS_KEY_ID=$TRAVIS_ACCESS_KEY_ID;
  - export TRAVIS_AWS_SECRET_ACCESS_KEY_ID=$TRAVIS_SECRET_ACCESS_KEY_ID;
script:
  gradle build
after_success:
  - mv build/libs/com-hy-0.0.1-SNAPSHOT.jar app.jar
  - zip latest.zip app.jar
  - zip -u latest.zip scripts/*
  - zip -u latest.zip appspec.yml
  - test -d dp_upload || mkdir dp_upload
  - mv latest.zip dp_upload/latest.zip
deploy:
  - provider: s3
    access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
    secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY_ID
    local_dir: dp_upload
    skip_cleanup: true
    on:
      branch: master
    bucket: "hyl-emp"
    region: us-west-2
  - provider: codedeploy
    access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
    secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY_ID
    bucket: "hyl-emp"
    key: latest.zip
    application: hyl-p1
    deployment_group: hyl-p1
    region: us-west-2
    on:
      branch: master


notifications:
    email:
        recipients:
            - t8440304@gmail.com
        on_success: always
        on_failure: always