version: 0.0
os: linux
files:
  - source: app.jar
    destination: /usr/bin/hylapp

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300